# Generated by Django 3.2 on 2022-12-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth0', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='idx',
            new_name='id',
        ),
    ]
