# Generated by Django 3.2 on 2022-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0', '0002_rename_idx_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_google_linked',
            field=models.BooleanField(default=False, verbose_name='Google Link'),
        ),
    ]
