# Generated by Django 3.2 on 2022-12-02 11:02

import auth0.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0', '0003_myuser_is_google_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to=auth0.models.image_upload_path),
        ),
    ]
