# Generated by Django 3.2 on 2022-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0', '0004_myuser_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ep',
            field=models.PositiveIntegerField(default=0, verbose_name='ePatra Points'),
        ),
    ]
