# Generated by Django 3.2 on 2022-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_liked_by'),
        ('reviews', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(related_name='reviews', to='news.Tag'),
        ),
    ]
