# Generated by Django 3.2 on 2022-12-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News or Article', 'verbose_name_plural': 'News or Articles'},
        ),
    ]
