# Generated by Django 3.2 on 2022-12-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
