# Generated by Django 3.2 on 2022-12-10 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_articles', related_query_name='deleted_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
