# Generated by Django 3.2 on 2022-12-11 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_articles', related_query_name='article', to=settings.AUTH_USER_MODEL),
        ),
    ]
