# Generated by Django 3.2 on 2022-12-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_liked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-created_on',)},
        ),
    ]
