# Generated by Django 3.2 on 2022-12-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20221213_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_on',), 'verbose_name': 'News or Article', 'verbose_name_plural': 'News or Articles'},
        ),
    ]
